Foundations of Data Science 
HW1 Jupyter Notebook
Yihang Ding, yd2459
yd2459@columbia.edu

Creates an array with the following daily temperature readings in Faren-
heit. (50,54,66,81,80,84,85,67,45,40,42,38,50,40,30,20,25,35,40).
• Convert the array to Centigrade
• Print the average temperature.
• Print the maximum and minimum temperatures
• Print the number of days in which the temperature is more than the day before
• Print the biggest percentage increase and the biggest percentage decrease
The jupyter notebook should intersprese text (the questions answered) and code to compute the quantities listed above.

In [13]:
temp_h=[50,54,66,81,80,84,85,67,45,40,42,38,50,40,30,20,25,35,40]

In [14]:
#1. Convert the array to Centigrade
#F=32+1.8×C
temp_c=temp_h.copy()
temp_c=[round((item-32)/1.8,2) for item in temp_c]
temp_c

[10.0,
 12.22,
 18.89,
 27.22,
 26.67,
 28.89,
 29.44,
 19.44,
 7.22,
 4.44,
 5.56,
 3.33,
 10.0,
 4.44,
 -1.11,
 -6.67,
 -3.89,
 1.67,
 4.44]

 answer: Temperature in Centigrade: [10.0, 12.22, 18.89, 27.22, 26.67, 28.89, 29.44, 19.44, 7.22, 4.44, 5.56, 3.33,
 10.0, 4.44, -1.11, -6.67, -3.89, 1.67, 4.44]

In [15]:
#2. Print the average temperature
avg_temp=round(sum(temp_h)/len(temp_h),2)
avg_temp

51.16

answer: The average temperature is 51.16 F

In [16]:
#3. Print the maximum and minimum temperatures
temp_h_tmp=temp_h.copy()
temp_h_tmp.sort()
print("Answer: Maximun temperature is "+str(temp_h_tmp[-1])+", lowest temperature is "+str(temp_h_tmp[0]))

Answer: Maximun temperature is 85, lowest temperature is 20


Answer: Maximun temperature is 85, lowest temperature is 20

In [17]:
#4. Print the number of days in which the temperature is more than the day before
num=0
for i,item in enumerate(temp_h[:-2]):
    if temp_h[i+1]>item:
        num+=1
print("Answer: the number of days in which the temperature is more than the day before is "+str(num))      

Answer: the number of days in which the temperature is more than the day before is 9


Answer: the number of days in which the temperature is more than the day before is 9

In [18]:
#5. Print the biggest percentage increase and the biggest percentage decrease
inc=0.0
dec=0.0
for i,item in enumerate(temp_h[:-2]):
    change=(temp_h[i+1]-item)/item*100
    if change>0 and change > inc:
        inc=change
    elif change<0 and change < dec:
        dec=change
print("Answer: the biggest percentage increase is "+str(round(inc,2))+ ", and the biggest percentage decrease is "+str(round(dec,2)))

Answer: the biggest percentage increase is 40.0, and the biggest percentage decrease is -33.33


Answer: the biggest percentage increase is 40.0, and the biggest percentage decrease is -33.33